import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { routeTree } from './routeTree.gen' // Generated by the Vite plugin
import './index.css'

// 1. Initialize Query Client
const queryClient = new QueryClient()

// 2. Initialize Router with the generated Route Tree
const router = createRouter({ 
  routeTree,
  context: {
    queryClient, // This allows routes to access the cache
  },
})

// 3. Register the router for type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>,
)
